/* tslint:disable */
/* eslint-disable */
/**
 * Pharmacy Product Api
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpartla@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface Pharmacy
 */
export interface Pharmacy {
    /**
     * 
     * @type {string}
     * @memberof Pharmacy
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Pharmacy
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Pharmacy
     */
    address?: string;
    /**
     * 
     * @type {Array<Product>}
     * @memberof Pharmacy
     */
    products?: Array<Product>;
    /**
     * 
     * @type {Array<Category>}
     * @memberof Pharmacy
     */
    predefinedCategories?: Array<Category>;
}

/**
 * Check if a given object implements the Pharmacy interface.
 */
export function instanceOfPharmacy(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function PharmacyFromJSON(json: any): Pharmacy {
    return PharmacyFromJSONTyped(json, false);
}

export function PharmacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pharmacy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'products': !exists(json, 'products') ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
        'predefinedCategories': !exists(json, 'predefinedCategories') ? undefined : ((json['predefinedCategories'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function PharmacyToJSON(value?: Pharmacy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'address': value.address,
        'products': value.products === undefined ? undefined : ((value.products as Array<any>).map(ProductToJSON)),
        'predefinedCategories': value.predefinedCategories === undefined ? undefined : ((value.predefinedCategories as Array<any>).map(CategoryToJSON)),
    };
}

