/* tslint:disable */
/* eslint-disable */
/**
 * Pharmacy Product Api
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpartla@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Unique id of the product within the pharmacy
     * @type {string}
     * @memberof Product
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name: string;
    /**
     * 
     * @type {Category}
     * @memberof Product
     */
    category?: Category;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    stock: number;
    /**
     * Soft-delete flag; the listing endpoint hides inactive products.
     * @type {boolean}
     * @memberof Product
     */
    active: boolean;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "stock" in value;
    isInstance = isInstance && "active" in value;

    return isInstance;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'category': !exists(json, 'category') ? undefined : CategoryFromJSON(json['category']),
        'stock': json['stock'],
        'active': json['active'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'category': CategoryToJSON(value.category),
        'stock': value.stock,
        'active': value.active,
    };
}

