/* tslint:disable */
/* eslint-disable */
/**
 * Pharmacy Product Api
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpartla@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Product,
} from '../models';
import {
    ProductFromJSON,
    ProductToJSON,
} from '../models';

export interface CreateProductRequest {
    pharmacyId: string;
    product: Product;
}

export interface DeleteProductRequest {
    pharmacyId: string;
    productId: string;
}

export interface GetProductRequest {
    pharmacyId: string;
    productId: string;
}

export interface GetProductsRequest {
    pharmacyId: string;
}

export interface UpdateProductRequest {
    pharmacyId: string;
    productId: string;
    product: Product;
}

/**
 * PharmacyProductsApi - interface
 * 
 * @export
 * @interface PharmacyProductsApiInterface
 */
export interface PharmacyProductsApiInterface {
    /**
     * Use this method to add a new product to the pharmacy inventory.
     * @summary Saves new product into the pharmacy
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {Product} product Product to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyProductsApiInterface
     */
    createProductRaw(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Use this method to add a new product to the pharmacy inventory.
     * Saves new product into the pharmacy
     */
    createProduct(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Soft delete. The product\'s `active` flag is set to false; it stays in the pharmacy.products array but is hidden from the listing endpoint.
     * @summary Soft-deletes a product (sets active=false)
     * @param {string} pharmacyId 
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyProductsApiInterface
     */
    deleteProductRaw(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Soft delete. The product\'s `active` flag is set to false; it stays in the pharmacy.products array but is hidden from the listing endpoint.
     * Soft-deletes a product (sets active=false)
     */
    deleteProduct(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using pharmacyId and productId you can read details of one product.
     * @summary Provides details about a single product
     * @param {string} pharmacyId 
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyProductsApiInterface
     */
    getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * By using pharmacyId and productId you can read details of one product.
     * Provides details about a single product
     */
    getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Returns the list of products of the pharmacy. Only active products are returned; soft-deleted (active=false) products are hidden.
     * @summary Provides the pharmacy product list
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyProductsApiInterface
     */
    getProductsRaw(requestParameters: GetProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Product>>>;

    /**
     * Returns the list of products of the pharmacy. Only active products are returned; soft-deleted (active=false) products are hidden.
     * Provides the pharmacy product list
     */
    getProducts(requestParameters: GetProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Product>>;

    /**
     * Use this method to update name, category, stock or active flag of a product.
     * @summary Updates specific product
     * @param {string} pharmacyId 
     * @param {string} productId 
     * @param {Product} product Updated product
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyProductsApiInterface
     */
    updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Use this method to update name, category, stock or active flag of a product.
     * Updates specific product
     */
    updateProduct(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

}

/**
 * 
 */
export class PharmacyProductsApi extends runtime.BaseAPI implements PharmacyProductsApiInterface {

    /**
     * Use this method to add a new product to the pharmacy inventory.
     * Saves new product into the pharmacy
     */
    async createProductRaw(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling createProduct.');
        }

        if (requestParameters.product === null || requestParameters.product === undefined) {
            throw new runtime.RequiredError('product','Required parameter requestParameters.product was null or undefined when calling createProduct.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/products/{pharmacyId}/items`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductToJSON(requestParameters.product),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Use this method to add a new product to the pharmacy inventory.
     * Saves new product into the pharmacy
     */
    async createProduct(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.createProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft delete. The product\'s `active` flag is set to false; it stays in the pharmacy.products array but is hidden from the listing endpoint.
     * Soft-deletes a product (sets active=false)
     */
    async deleteProductRaw(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling deleteProduct.');
        }

        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling deleteProduct.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products/{pharmacyId}/items/{productId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete. The product\'s `active` flag is set to false; it stays in the pharmacy.products array but is hidden from the listing endpoint.
     * Soft-deletes a product (sets active=false)
     */
    async deleteProduct(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProductRaw(requestParameters, initOverrides);
    }

    /**
     * By using pharmacyId and productId you can read details of one product.
     * Provides details about a single product
     */
    async getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling getProduct.');
        }

        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling getProduct.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products/{pharmacyId}/items/{productId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * By using pharmacyId and productId you can read details of one product.
     * Provides details about a single product
     */
    async getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.getProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the list of products of the pharmacy. Only active products are returned; soft-deleted (active=false) products are hidden.
     * Provides the pharmacy product list
     */
    async getProductsRaw(requestParameters: GetProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Product>>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling getProducts.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products/{pharmacyId}/items`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * Returns the list of products of the pharmacy. Only active products are returned; soft-deleted (active=false) products are hidden.
     * Provides the pharmacy product list
     */
    async getProducts(requestParameters: GetProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Product>> {
        const response = await this.getProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to update name, category, stock or active flag of a product.
     * Updates specific product
     */
    async updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling updateProduct.');
        }

        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling updateProduct.');
        }

        if (requestParameters.product === null || requestParameters.product === undefined) {
            throw new runtime.RequiredError('product','Required parameter requestParameters.product was null or undefined when calling updateProduct.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/products/{pharmacyId}/items/{productId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProductToJSON(requestParameters.product),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Use this method to update name, category, stock or active flag of a product.
     * Updates specific product
     */
    async updateProduct(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.updateProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
