/* tslint:disable */
/* eslint-disable */
/**
 * Pharmacy Product Api
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpartla@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Pharmacy,
} from '../models';
import {
    PharmacyFromJSON,
    PharmacyToJSON,
} from '../models';

export interface CreatePharmacyRequest {
    pharmacy: Pharmacy;
}

export interface DeletePharmacyRequest {
    pharmacyId: string;
}

/**
 * PharmaciesApi - interface
 * 
 * @export
 * @interface PharmaciesApiInterface
 */
export interface PharmaciesApiInterface {
    /**
     * Use this method to initialize new pharmacy in the system
     * @summary Saves new pharmacy definition
     * @param {Pharmacy} pharmacy Pharmacy details to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmaciesApiInterface
     */
    createPharmacyRaw(requestParameters: CreatePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pharmacy>>;

    /**
     * Use this method to initialize new pharmacy in the system
     * Saves new pharmacy definition
     */
    createPharmacy(requestParameters: CreatePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pharmacy>;

    /**
     * Use this method to delete the specific pharmacy from the system.
     * @summary Deletes specific pharmacy
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmaciesApiInterface
     */
    deletePharmacyRaw(requestParameters: DeletePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete the specific pharmacy from the system.
     * Deletes specific pharmacy
     */
    deletePharmacy(requestParameters: DeletePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class PharmaciesApi extends runtime.BaseAPI implements PharmaciesApiInterface {

    /**
     * Use this method to initialize new pharmacy in the system
     * Saves new pharmacy definition
     */
    async createPharmacyRaw(requestParameters: CreatePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pharmacy>> {
        if (requestParameters.pharmacy === null || requestParameters.pharmacy === undefined) {
            throw new runtime.RequiredError('pharmacy','Required parameter requestParameters.pharmacy was null or undefined when calling createPharmacy.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/pharmacy`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PharmacyToJSON(requestParameters.pharmacy),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PharmacyFromJSON(jsonValue));
    }

    /**
     * Use this method to initialize new pharmacy in the system
     * Saves new pharmacy definition
     */
    async createPharmacy(requestParameters: CreatePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pharmacy> {
        const response = await this.createPharmacyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete the specific pharmacy from the system.
     * Deletes specific pharmacy
     */
    async deletePharmacyRaw(requestParameters: DeletePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling deletePharmacy.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete the specific pharmacy from the system.
     * Deletes specific pharmacy
     */
    async deletePharmacy(requestParameters: DeletePharmacyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePharmacyRaw(requestParameters, initOverrides);
    }

}
