/* tslint:disable */
/* eslint-disable */
/**
 * Pharmacy Product Api
 * Pharmacy product inventory for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpartla@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Category,
} from '../models';
import {
    CategoryFromJSON,
    CategoryToJSON,
} from '../models';

export interface GetCategoriesRequest {
    pharmacyId: string;
}

/**
 * PharmacyCategoriesApi - interface
 * 
 * @export
 * @interface PharmacyCategoriesApiInterface
 */
export interface PharmacyCategoriesApiInterface {
    /**
     * By using pharmacyId you get the list of predefined product categories.
     * @summary Provides the list of categories defined for the pharmacy
     * @param {string} pharmacyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyCategoriesApiInterface
     */
    getCategoriesRaw(requestParameters: GetCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Category>>>;

    /**
     * By using pharmacyId you get the list of predefined product categories.
     * Provides the list of categories defined for the pharmacy
     */
    getCategories(requestParameters: GetCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Category>>;

}

/**
 * 
 */
export class PharmacyCategoriesApi extends runtime.BaseAPI implements PharmacyCategoriesApiInterface {

    /**
     * By using pharmacyId you get the list of predefined product categories.
     * Provides the list of categories defined for the pharmacy
     */
    async getCategoriesRaw(requestParameters: GetCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Category>>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling getCategories.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products/{pharmacyId}/categories`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryFromJSON));
    }

    /**
     * By using pharmacyId you get the list of predefined product categories.
     * Provides the list of categories defined for the pharmacy
     */
    async getCategories(requestParameters: GetCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Category>> {
        const response = await this.getCategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
