/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XpartlaPharmacyProductApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        "pharmacyId": string;
    }
    interface XpartlaPharmacyProductEditor {
        "apiBase": string;
        "pharmacyId": string;
        "productId": string;
    }
    interface XpartlaPharmacyProductList {
        "apiBase": string;
        "pharmacyId": string;
    }
}
export interface XpartlaPharmacyProductEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpartlaPharmacyProductEditorElement;
}
export interface XpartlaPharmacyProductListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpartlaPharmacyProductListElement;
}
declare global {
    interface HTMLXpartlaPharmacyProductAppElement extends Components.XpartlaPharmacyProductApp, HTMLStencilElement {
    }
    var HTMLXpartlaPharmacyProductAppElement: {
        prototype: HTMLXpartlaPharmacyProductAppElement;
        new (): HTMLXpartlaPharmacyProductAppElement;
    };
    interface HTMLXpartlaPharmacyProductEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXpartlaPharmacyProductEditorElement extends Components.XpartlaPharmacyProductEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpartlaPharmacyProductEditorElementEventMap>(type: K, listener: (this: HTMLXpartlaPharmacyProductEditorElement, ev: XpartlaPharmacyProductEditorCustomEvent<HTMLXpartlaPharmacyProductEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpartlaPharmacyProductEditorElementEventMap>(type: K, listener: (this: HTMLXpartlaPharmacyProductEditorElement, ev: XpartlaPharmacyProductEditorCustomEvent<HTMLXpartlaPharmacyProductEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpartlaPharmacyProductEditorElement: {
        prototype: HTMLXpartlaPharmacyProductEditorElement;
        new (): HTMLXpartlaPharmacyProductEditorElement;
    };
    interface HTMLXpartlaPharmacyProductListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLXpartlaPharmacyProductListElement extends Components.XpartlaPharmacyProductList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpartlaPharmacyProductListElementEventMap>(type: K, listener: (this: HTMLXpartlaPharmacyProductListElement, ev: XpartlaPharmacyProductListCustomEvent<HTMLXpartlaPharmacyProductListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpartlaPharmacyProductListElementEventMap>(type: K, listener: (this: HTMLXpartlaPharmacyProductListElement, ev: XpartlaPharmacyProductListCustomEvent<HTMLXpartlaPharmacyProductListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpartlaPharmacyProductListElement: {
        prototype: HTMLXpartlaPharmacyProductListElement;
        new (): HTMLXpartlaPharmacyProductListElement;
    };
    interface HTMLElementTagNameMap {
        "xpartla-pharmacy-product-app": HTMLXpartlaPharmacyProductAppElement;
        "xpartla-pharmacy-product-editor": HTMLXpartlaPharmacyProductEditorElement;
        "xpartla-pharmacy-product-list": HTMLXpartlaPharmacyProductListElement;
    }
}
declare namespace LocalJSX {
    interface XpartlaPharmacyProductApp {
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
        "pharmacyId"?: string;
    }
    interface XpartlaPharmacyProductEditor {
        "apiBase"?: string;
        "onEditor-closed"?: (event: XpartlaPharmacyProductEditorCustomEvent<string>) => void;
        "pharmacyId"?: string;
        "productId"?: string;
    }
    interface XpartlaPharmacyProductList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: XpartlaPharmacyProductListCustomEvent<string>) => void;
        "pharmacyId"?: string;
    }

    interface XpartlaPharmacyProductAppAttributes {
        "basePath": string;
        "apiBase": string;
        "pharmacyId": string;
    }
    interface XpartlaPharmacyProductEditorAttributes {
        "productId": string;
        "pharmacyId": string;
        "apiBase": string;
    }
    interface XpartlaPharmacyProductListAttributes {
        "apiBase": string;
        "pharmacyId": string;
    }

    interface IntrinsicElements {
        "xpartla-pharmacy-product-app": Omit<XpartlaPharmacyProductApp, keyof XpartlaPharmacyProductAppAttributes> & { [K in keyof XpartlaPharmacyProductApp & keyof XpartlaPharmacyProductAppAttributes]?: XpartlaPharmacyProductApp[K] } & { [K in keyof XpartlaPharmacyProductApp & keyof XpartlaPharmacyProductAppAttributes as `attr:${K}`]?: XpartlaPharmacyProductAppAttributes[K] } & { [K in keyof XpartlaPharmacyProductApp & keyof XpartlaPharmacyProductAppAttributes as `prop:${K}`]?: XpartlaPharmacyProductApp[K] };
        "xpartla-pharmacy-product-editor": Omit<XpartlaPharmacyProductEditor, keyof XpartlaPharmacyProductEditorAttributes> & { [K in keyof XpartlaPharmacyProductEditor & keyof XpartlaPharmacyProductEditorAttributes]?: XpartlaPharmacyProductEditor[K] } & { [K in keyof XpartlaPharmacyProductEditor & keyof XpartlaPharmacyProductEditorAttributes as `attr:${K}`]?: XpartlaPharmacyProductEditorAttributes[K] } & { [K in keyof XpartlaPharmacyProductEditor & keyof XpartlaPharmacyProductEditorAttributes as `prop:${K}`]?: XpartlaPharmacyProductEditor[K] };
        "xpartla-pharmacy-product-list": Omit<XpartlaPharmacyProductList, keyof XpartlaPharmacyProductListAttributes> & { [K in keyof XpartlaPharmacyProductList & keyof XpartlaPharmacyProductListAttributes]?: XpartlaPharmacyProductList[K] } & { [K in keyof XpartlaPharmacyProductList & keyof XpartlaPharmacyProductListAttributes as `attr:${K}`]?: XpartlaPharmacyProductListAttributes[K] } & { [K in keyof XpartlaPharmacyProductList & keyof XpartlaPharmacyProductListAttributes as `prop:${K}`]?: XpartlaPharmacyProductList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xpartla-pharmacy-product-app": LocalJSX.IntrinsicElements["xpartla-pharmacy-product-app"] & JSXBase.HTMLAttributes<HTMLXpartlaPharmacyProductAppElement>;
            "xpartla-pharmacy-product-editor": LocalJSX.IntrinsicElements["xpartla-pharmacy-product-editor"] & JSXBase.HTMLAttributes<HTMLXpartlaPharmacyProductEditorElement>;
            "xpartla-pharmacy-product-list": LocalJSX.IntrinsicElements["xpartla-pharmacy-product-list"] & JSXBase.HTMLAttributes<HTMLXpartlaPharmacyProductListElement>;
        }
    }
}
